stages:
  - gather
  - integrate
  - build
  - deploy

variables:
  INTEGRATOR_VERSION: "1.0.3"
  INTEGRATOR_URL: "${CI_API_V4_URL}/projects/21002959/packages/generic/integrator/${INTEGRATOR_VERSION}/bulk_integrator"
  OAS_REPO_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/i3-market/code/wp4/backplane-subsystems-oas.git"
  SECRETS_URL: "http://95.211.3.251:8081/repository/i3m-raw/backplane/env/secrets.json"
  ANSIBLE_BACKPLANE_JOB_URL: "http://95.211.3.249:19000/api/v2/job_templates/13/launch/"
  ANSIBLE_SDK_JOB_URL: "http://95.211.3.249:19000/api/v2/job_templates/24/launch/"


get-integrator:
  stage: gather
  image: curlimages/curl:latest
  script:
    - 'curl --request GET --header "JOB-TOKEN: $CI_JOB_TOKEN" "${INTEGRATOR_URL}"'
    - chmod +x ./bulk_integrator
  artifacts:
    paths:
      - bulk_integrator
    expire_in: 10 mins

get-secrets:
  stage: gather
  image: curlimages/curl:latest
  script:
    - echo $NEXUS_PASSWORD | curl --request GET -u '$NEXUS_USER' $SECRETS_URL
    - mv secrets.json .secrets.json
  artifacts:
    paths:
      - .secrets.json
    expire_in: 10 mins

get-subsystems-oas:
  stage: gather
  script:
    - git clone $OAS_REPO_URL ./specs
  artifacts:
    paths:
      - specs/
    exclude:
      - specs/.gitlab-ci.yml
      - specs/.git
      - spect/README.md
    expire_in: 10 mins


integrate-subsystems:
  stage: integrate
  image: node:15-slim
  script:
    - npm i -g @loopback/cli@2.15.1
    - ./bulk_integrator . ./specs
  artifacts:
    untracked: true
    paths:
      - src/controllers/index.ts
      - src/datasources/index.ts
      - src/models/index.ts
      - src/repositories/index.ts
      - src/services/index.ts
      - .secrets.json
    expire_in: 10 mins


build:
  stage: build
  image:
    name: docker:19.03.13
  services:
    - name: docker:19.03.13-dind
      entrypoint: ["sh", "-c", "dockerd-entrypoint.sh --insecure-registry=$DOCKER_REGISTRY"]
  variables:
    NEXUS_REGISTRY: "95.211.3.251:8123"
    NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/backplane:latest
    DOCKER_TLS_CERTDIR: ""
    GITLAB_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  before_script:
    - echo "$NEXUS_PASSWORD" | docker login $NEXUS_REGISTRY --username $NEXUS_USER --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $NEXUS_IMAGE_TAG -t $GITLAB_IMAGE_TAG .
    - docker push $NEXUS_IMAGE_TAG
    - docker push $GITLAB_IMAGE_TAG


update-secrets:
  stage: build
  script:
    - echo $NEXUS_PASSWORD | curl --request PUT -u '$NEXUS_USER' --upload-file .secrets.json $SECRETS_URL


deploy-ansible-backend:
  stage: deploy
  script:
    - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$ANSIBLE_BACKPLANE_JOB_URL"'

deploy-ansible-sdk:
  stage: deploy
  only:
    - master
  script:
    - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$ANSIBLE_SDK_JOB_URL"'
