version: "3.8"

services:
  backplane-with-integrator:
    build:
      context: .
      args:
        ADD_INTEGRATOR: 1
        GITLAB_USER: ${GITLAB_USER}
        GITLAB_TOKEN: ${GITLAB_TOKEN}
    container_name: backplane-test
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      OIDC_CLIENT_ID: ${BACKPLANE_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${BACKPLANE_OIDC_CLIENT_SECRET}
      OIDC_PROVIDER_WELL_KNOWN_URL: ${BACKPLANE_OIDC_PROVIDER_WELL_KNOWN_URL}
    volumes:
      - ./specs:/specs
    command: /bin/bash -c "/integrator/bulk_integrator . /specs && npm run build && node ."

  backplane:
    build: .
    image: backplane:latest
    env_file:
#      - <path to .env file>
      - .env
    environment:
      CERTS_PATH: /certificates
      SECRETS_PATH: /.secrets.json
    ports:
      - "3000:3000"
    volumes:
#      Change "./certificates" below for the path containing the certificates
#      - <path to certificates directory>:/certificates
      - ./certificates:/certificates
#      Change "./.secrets.json" below for the path of the secrets.json file
#      - <path of secrets file>:/.secrets.json
      - ./.secrets.json:/.secrets.json